# This is a basic workflow to help you get started with Actions

name: Update

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Fetch
        uses: actions/checkout@v4
        with:
          repository: 'ojisandbox/actions-test-raw'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: raw
        run: |
          curl -o raw/known_exploited_vulnerabilities.json https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json
          cd raw
          git add .
          git commit --author "actions-user <action@github.com>" -m "update"
          git push
