# This is a basic workflow to help you get started with Actions

name: Update

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Fetch0
        uses: actions/checkout@v4
        with:
          path: tmp
      - run: |
          git config --global user.email "65916846+actions-user@users.noreply.github.com"
          git config --global user.name "actions-user"
          date > tmp/date.txt
          cd tmp
          git add .
          git commit -m "update"
          git push

      # Runs a single command using the runners shell
      - name: Get GitHub API token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MY_GITHUB_APP_ID }}
          private_key: ${{ secrets.MY_GITHUB_APP_PRIVATE_KEY }}
      - name: Fetch1
        uses: actions/checkout@v4
        with:
          repository: 'ojisandbox/actions-test-raw'
          path: raw
      - run: |
          git config --global user.email "65916846+actions-user@users.noreply.github.com"
          git config --global user.name "actions-user"
          git config --global url."https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/org-name/".insteadOf git@github.com:org-name/
          curl -o raw/known_exploited_vulnerabilities.json https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json
          cd raw
          git add .
          git commit -m "update"
          git push
